# Generated by Django 5.0.3 on 2024-03-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exam_images/'),
        ),
    ]
