# Generated by Django 5.0.3 on 2024-03-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_description_exam_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exam',
            new_name='Question',
        ),
    ]
