# Generated by Django 5.0.3 on 2024-03-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_question_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='auther',
            new_name='author',
        ),
    ]
